# syntax=docker/dockerfile:1

ARG RUBY_VERSION=3.3.11
FROM docker.io/library/ruby:${RUBY_VERSION}-slim

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential \
      curl \
      git \
      libpq-dev \
      libsqlite3-dev \
      libvips \
      libyaml-dev \
      pkg-config \
      postgresql-client \
      sqlite3 && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

RUN gem install bundler:4.0.12

ENV BUNDLE_PATH=/usr/local/bundle

COPY Gemfile Gemfile.lock ./
RUN bundle install

CMD ["bash"]
